version: "3.9"
services:
  db:
    image: postgres
    # environment:
    #   POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp:cached
      - /myapp/node_modules/
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    stdin_open: true
    tty: true
    # selenium_chrome を使うために以下の行を追加
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none
  # chrome:
  #   image: selenium/standalone-chrome:3.141.59-dubnium
  #   ports:
  #     - 4444:4444
  # node:
  #   image: node:alpine
  #   ports:
  #     - "8000:80"
  #   volumes:
  #     - ./:/src
  #   working_dir: /src
