version: 2.1
jobs:
  build:
    #自身のアプリ名にする
    working_directory: ~/ucmsapp1
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          POSTGRES_USER: postgres
          PGHOST: 127.0.0.1
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          BUNDLER_VERSION: 2.1.4
          DATABASE_URL: postgres://postgres:password@localhost:5432/ucms_app_test
          RAILS_ENV: test
      - image: circleci/postgres:latest
        environment:
          #それぞれ設定
          POSTGRES_USER: postgres
          #下記を書けばパスワードなしでデータベースにログインしてくれる。
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: ucms_app_test
      - image:
          selenium/standalone-chrome-debug
          # logging:
          #   driver: none
    steps:
      - checkout
      # bundle キャッシュをリストアする。公式の設定通り。
      - restore_cache:
          keys:
            - ucmsapp1-bundle-v1-{{ checksum "Gemfile.lock" }}
            - ucmsapp1-bundle-v1-
      # bundle install で依存関係をインストールする。
      - run:
          name: Bundler install
          command: |
            gem update --system
            gem install bundler -v 2.1.4
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      # bundle キャッシュを保存する
      - save_cache:
          key: ucmsapp1-bundle-v1-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - restore_cache:
          keys:
            - rails-demo-yarn-{{ checksum "yarn.lock" }}
            - rails-demo-yarn-
      - run:
          name: Yarnをinstall
          command: yarn install --cache-folder ~/.cache/yarn
      - run:
          name: sweetalert
          command: yarn add sweetalert
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
      - run:
          name: Database setup
          command: bin/rails db:migrate db:schema:load --trace
      - run: bundle exec bin/webpack
        #run rubocop
      # - run:
      #     name: Rubocop
      #     command: bundle exec rubocop
      # rspecを実行する
      - run:
          name: execute rspec
          command: bundle exec rspec
      - store_test_results:
          path: /tmp/test-results
